export const COMMANDS = {
    PLAYER_CONNECT: '@KAL/PLAYER_CONNECT',
    GAME_CREATE: '@KAL/GAME_CREATE',
    ROOM_CREATED: '@KAL/ROOM_CREATED',
    PLAYER_JOIN: '@KAL/PLAYER_JOIN',
    ROOM_EXPIRED: '@KAL/ROOM_EXPIRED',
    SET_USERNAME: '@KAL/SET_USERNAME',
    ROOM_JOINED: '@KAL/ROOM_JOINED',
    ROOM_RECONNECT: '@KAL/ROOM_RECONNECT',
    PLAYER_DISCONNECT: '@KAL/PLAYER_DISCONNECT',
    GAME_OVER: '@KAL/GAME_OVER',
}
